"""make_portfolio_user_id_nullable

Revision ID: 33a656bd8176
Revises: 4341e5463adc
Create Date: 2026-05-11 15:46:28.892694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a656bd8176'
down_revision: Union[str, None] = '4341e5463adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('portfolios_user_id_fkey', 'portfolios', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('portfolios_user_id_fkey', 'portfolios', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
