"""add_paired_ticker_to_companies

Revision ID: 3f201beb236d
Revises: a1b2c3d4e5f6
Create Date: 2026-05-13 17:37:06.501858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f201beb236d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PAIRS = [
    ("SBER", "SBERP"),
    ("TATN", "TATNP"),
    ("SNGS", "SNGSP"),
    ("BANE", "BANEP"),
    ("RTKM", "RTKMP"),
    ("LKOH", "LKOHP"),
    ("IRAO", "IRAOP"),
]


def upgrade() -> None:
    op.add_column('companies', sa.Column('paired_ticker', sa.String(length=10), nullable=True))

    conn = op.get_bind()
    for ao, ap in PAIRS:
        conn.execute(
            sa.text("UPDATE companies SET paired_ticker = :ap WHERE ticker = :ao"),
            {"ao": ao, "ap": ap},
        )
        conn.execute(
            sa.text("UPDATE companies SET paired_ticker = :ao WHERE ticker = :ap"),
            {"ao": ao, "ap": ap},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'paired_ticker')
    # ### end Alembic commands ###
