"""add_quote_change_fields

Revision ID: 4341e5463adc
Revises: eda712117ef8
Create Date: 2026-05-11 15:31:08.897744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4341e5463adc'
down_revision: Union[str, None] = 'eda712117ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('prev_close', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('quotes', sa.Column('change_abs', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('quotes', sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'change_pct')
    op.drop_column('quotes', 'change_abs')
    op.drop_column('quotes', 'prev_close')
    # ### end Alembic commands ###
