"""add_deep_analysis_fields_to_company_analyses

Revision ID: eda712117ef8
Revises: 6d9c4013f009
Create Date: 2026-05-10 01:30:40.655082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda712117ef8'
down_revision: Union[str, None] = '6d9c4013f009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_analyses', sa.Column('business_model', sa.JSON(), nullable=True))
    op.add_column('company_analyses', sa.Column('financials', sa.JSON(), nullable=True))
    op.add_column('company_analyses', sa.Column('competitors', sa.JSON(), nullable=True))
    op.add_column('company_analyses', sa.Column('macro_economy', sa.JSON(), nullable=True))
    op.add_column('company_analyses', sa.Column('global_economy', sa.JSON(), nullable=True))
    op.add_column('company_analyses', sa.Column('geopolitics', sa.JSON(), nullable=True))
    op.add_column('company_analyses', sa.Column('technical_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_analyses', 'technical_analysis')
    op.drop_column('company_analyses', 'geopolitics')
    op.drop_column('company_analyses', 'global_economy')
    op.drop_column('company_analyses', 'macro_economy')
    op.drop_column('company_analyses', 'competitors')
    op.drop_column('company_analyses', 'financials')
    op.drop_column('company_analyses', 'business_model')
    # ### end Alembic commands ###
